### ISSUE TITLE
Cypress failing on _sanity/README.md 

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#186]
After merging the new CI/CD changes I'm getting this error, which is super weird considering that nothing has been changed in terms of e2e tests.

```shell
Running:  app/_sanity/README.md                                                           (2 of 5)

Oops...we found an error preparing this test file:

  /__w/cypress/integration/app/_sanity/README.md

The error was:

Error: Webpack Compilation Error
./cypress/integration/app/_sanity/README.md 1:7
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> Sanity checks
| ===
|

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        0                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     app/_sanity/README.md    
```

For whatever reason cypress is trying to run the `_sanity/README.md` file.

Locally everything is fine though.

Any thoughts?

**Comment by samuelcastro** [comment]
Never mind, my config was missing: `"ignoreTestFiles": "*.md"`

**Comment by Vadorequest** [comment]
Glad you sorted it out 😄
